spring.application.name=gatewayX
spring.datasource.url=jdbc:postgresql://localhost:5432/gatewayx
spring.datasource.username=vivekrkumar
spring.datasource.password=Vivek@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

gatewayx.ratelimit.strategy=tokenBucket

jwt.secret=ThisIsATemporaryDevelopmentSecretKeyChangeInProduction123456
jwt.expiration=86400000
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=gatewayx-usage-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer